Added Some projects in Projects.json
Opentek-Org/opentek pull request #63
Opened 2021-09-21 11:41 UTC by sibteali786

2021-09-21 11:47 UTC, AnirudhPanda requested changes

2021-09-21 11:47 UTC, AnirudhPanda commented on data/projects.json
> +        "langName": "Certificate Generation and Verification System",
Any reason for this change?

2021-09-22 04:27 UTC, AnirudhPanda approved these changes

2021-09-26 07:25 UTC, AnirudhPanda commented
![image](https://user-images.githubusercontent.com/66218496/134798009-bc4993ed-8ee1-4849-a543-43c803844930.png)

In the second row, the bottom border radius is not seen, also sizing needs to be corrected!
@sibteali786

2021-09-26 13:15 UTC, sibteali786 commented
> ![image](https://user-images.githubusercontent.com/66218496/134798009-bc4993ed-8ee1-4849-a543-43c803844930.png)
> 
> In the second row, the bottom border radius is not seen, also sizing needs to be corrected!
> @sibteali786

Then a new issue will have to be created for resolving because it concerns designing

2021-09-28 06:45 UTC, merged